Repository JetBrains/swot, pull requests merged in 2024-09, with the labels that each got.

#23279 Add Montgomery County Community College to swot
  lib/domains/edu/mc3.txt
Labels: failed

#23629 Add Allan Blakeney Adult Campus
  lib/domains/ca/sk/rbe.txt
Labels: in progress

#23585 Adding Marvin Ridge Middle School from North Carolina, USA
  lib/domains/us/nc/k12/ucps/student.txt
Labels: in progress

#23624 Create idat.txt
  lib/domains/pe/idat.txt
Labels: in progress

#23639 Merge Unifeb
  lib/domains/br/edu/unifeb.txt
Labels: in progress

#23638 Pull request for fsr.ac.ma
  lib/domains/ma/ac/fsr.txt
Labels: in progress

#23612 Add NASOA university
  lib/domains/ua/edu/nasoa.txt
Labels: in progress

#23570 Add files via upload
  lib/domains/schule/sbsz-bamberg.txt
Labels: in progress

#23408 Add notredamevalenciennes
  lib/domains/fr/notredamevalenciennes.txt
Labels: in progress

#23496 Request to Add "IMS Noida" to GitHub Student Developer Pack
  lib/domains/com/imsnoida.txt
Labels: in progress

#23492 Add files via upload
  lib/domains/br/com/beityaacov.txt
Labels: in progress

#23644 Add files via upload
  lib/domains/au/edu/qld/riverside.txt
Labels: in progress

#23711 edu.karstula.fi
  lib/domains/fi/karstula/edu.txt
Labels: in progress

#23692 Add domain for FDFZ
  lib/domains/cn/fdfz.txt
Labels: in progress

#23697 Added BSZ-Wiesau students domain
  lib/domains/com/onmicrosoft/bswiesaude.txt
Labels: in progress

#23700 Add files via upload
  lib/domains/uk/sch/bucks/jhgs.txt
Labels: in progress

#23703 Create bbs-cux.txt
  lib/domains/eu/bbs-cux.txt
Labels: in progress

#23709 Add files via upload
  lib/domains/th/ac/onehope.txt
Labels: in progress

#23720 Add ASU
  lib/domains/eg/edu/asu/alsun/std.txt
Labels: in progress

#23721 Al Azhar University
  lib/domains/eg/edu/azhar.txt
Labels: in progress

#23730 Add dsbarcelona.com
  lib/domains/com/dsbarcelona.txt
Labels: in progress

#23719 Add CREF domain
  lib/domains/it/cref.txt
Labels: in progress

#23722 Create mechwart.txt
  lib/domains/com/mechwart.txt
Labels: in progress

#23726 Add files via upload
  lib/domains/pl/sp1mragowo.txt
Labels: in progress

#23728 Add ENSBA
  lib/domains/fr/ensba-lyon.txt
Labels: in progress

#23735 adding file of Escuela Superior Franciscana Especializada/Agape
  lib/domains/sv/edu/agape/esfe.txt
Labels: in progress

#23808 THPT Yên Viên
  lib/domains/vn/edu/thptyenvien.txt
Labels: in progress

#23847 UH
  lib/domains/edu/uh/cougarnet.txt
Labels: malformatted

#23750 Adding ESZI as an IT school
  lib/domains/hu/eszi.txt
Labels: in progress

#23756 Add ECI - École de commerce et d'informatique
  lib/domains/info/eci-liege.txt
Labels: in progress

#23751 North East Futures changed domain.
  lib/domains/academy/tynecoast/nef.txt
  lib/domains/uk/co/nefuturesutc.txt
Labels: in progress

#23753 Add Pelgulinna State Upper Secondary School
  lib/domains/ee/perg.txt
Labels: in progress

#23804 Add domain zsl.poznan.pl
  lib/domains/pl/poznan/zsl.txt
Labels: in progress

#23767 The Ruth Gorse Academy
  lib/domains/uk/sch/leeds/ruthgorse.txt
Labels: in progress

#23773 Added UNICEUG university
  lib/domains/br/com/uniceug/aluno.txt
Labels: in progress

#23772 Trying to add ITE to JetBrains school list
  lib/domains/br/edu/ite.txt
Labels: in progress

#23637 Add new students email Florida Universitaria
  lib/domains/es/alumnatflorida.txt
Labels: in progress

#23784 Adding Colégio Técnico da UFMG - COLTEC
  lib/domains/org/teiacoltec.txt
Labels: in progress

#23795 Stratford Schools School Addition
  lib/domains/com/stratfordschools.txt
Labels: in progress

#23811 Adding Technical School 'Ivan Sarić'
  lib/domains/rs/edu/tsis.txt
Labels: in progress

#23819 Add dandenong high school to domains
  lib/domains/au/edu/vic/dandenong-hs.txt
Labels: in progress

#23833 Midocean University
  lib/domains/km/edu/midocean/st.txt
Labels: in progress

#23845 cnmvturda.txt
  lib/domains/ro/cnmvturda.txt
Labels: in progress

#23820 Add files via upload
  lib/domains/vn/edu/sis.txt
Labels: in progress

#23885 Add lisoft.edu.pe
  lib/domains/pe/edu/lisoft.txt
Labels: in progress

#23892 Create kg121
  lib/domains/education/ukr/kg121.txt
Labels: in progress

#23852 Create bu.txt
  lib/domains/eg/edu/bu.txt
Labels: in progress

#23861 Add .be for ECI
  lib/domains/be/eci-liege.txt
Labels: in progress

#23870 Add I Lo ozorkow
  lib/domains/pl/edu/lo-ozorkow.txt
Labels: in progress

#23879 Create cegepmv.txt
  lib/domains/ca/cegepmv.txt
Labels: in progress
