Repository JetBrains/swot, pull requests merged in 2025-03, with the labels that each got.

#27769 Add files via upload
  lib/domains/fr/student-oec.txt
Labels: in progress

#27551 added Galgotias University
  lib/domains/in/ac/galgotiasuniversity.txt
Labels: in progress

#27558 Adding FSEGN faculty
  lib/domains/tn/ucar/fsegn.txt
Labels: in progress

#27556 Add IV Liceum Ogólnokształcące im. Komisji Edukacji Narodowej
  lib/domains/pl/poznan/lo4/edu.txt
Labels: in progress

#27617 Add files via upload
  lib/domains/ar/edu/galileo.txt
Labels: in progress

#27572 Add files via upload
  lib/domains/in/ac/iiitkottayam.txt
Labels: in progress

#27957 Add Integral University (iul.ac.in)
  lib/domains/in/ac/iul.txt
Labels: failed

#27733 Adding the domains of "Institute of Chemical Technology" (All Campus)
  lib/domains/in/edu/ictmumbai.txt
  lib/domains/in/edu/ictmumbai/faculty.txt
  lib/domains/in/edu/ictmumbai/iocb.txt
  lib/domains/in/edu/ictmumbai/marj.txt
  lib/domains/in/edu/ictmumbai/pg.txt
  lib/domains/in/edu/ictmumbai/staff.txt
  lib/domains/in/edu/ictmumbai/staffiocb.txt
  lib/domains/in/edu/ictmumbai/staffmarj.txt
  lib/domains/in/edu/ictmumbai/stuiocb.txt
  lib/domains/in/edu/ictmumbai/stumarj.txt
  lib/domains/in/edu/ictmumbai/ug.txt
Labels: in progress

#27801 Create uigv
  lib/domains/pe/uigv.txt
Labels: in progress

#27862 add СЭЗИС's new mail
  lib/domains/mn/edu/ufenu.txt
Labels: in progress

#27660 Add Zakir Husain College of Engineering and Technology to lib.
  lib/domains/in/ac/zhcet.txt
Labels: in progress

#27681 Added various NITS departments
  lib/domains/in/ac/nits.txt
  lib/domains/in/ac/nits/che.txt
  lib/domains/in/ac/nits/civil.txt
  lib/domains/in/ac/nits/cse.txt
  lib/domains/in/ac/nits/ece.txt
  lib/domains/in/ac/nits/ei.txt
  lib/domains/in/ac/nits/hum.txt
  lib/domains/in/ac/nits/math.txt
  lib/domains/in/ac/nits/mba.txt
  lib/domains/in/ac/nits/mech.txt
  lib/domains/in/ac/nits/phy.txt
Labels: in progress

#27845 Add Faculdade Melies
  lib/domains/br/com/alunomelies.txt
Labels: in progress

#27668 School
  lib/domains/id/go/kemenag.txt
Labels: in progress

#28003 Ecole Nationale d'Administration
  lib/domains/ci/edu/ena.txt
Labels: in progress

#27804 add school
  lib/domains/br/gov/ce/aluno.txt
Labels: in progress

#28016 Rødovre Gymnasium
  lib/domains/dk/rg/rgnet.txt
Labels: in progress

#28006 Add Masconomet Regional High School
  lib/domains/org/mrsdmail.txt
Labels: in progress

#27888 Create file istitutodionigiscano.txt
  lib/domains/org/istitutodionigiscano.txt
Labels: in progress

#27720 Added fgs-bln.txt
  lib/domains/de/fgs-bln.txt
Labels: in progress

#27497 Create academia-ciberseguridad
  lib/domains/com/academia-ciberseguridad.txt
Labels: in progress

#28018 add Sarvajanik College of Engineering and Technology, Surat
  lib/domains/in/ac/scet.txt
Labels: in progress

#27966 Create gecg28.txt
  lib/domains/in/ac/gecg28.txt
Labels: in progress

#27758 Sri Sairam Of Institute of technology
  lib/domains/in/edu/sairamtap.txt
Labels: in progress

#27743 adding domain mitsgwl.ac.in
  lib/domains/in/ac/mitsgwl.txt
Labels: in progress

#27914 Add fikr.edu.sa, modify fikrgs.edu.sa
  lib/domains/sa/edu/fikr.txt
  lib/domains/sa/edu/fikrgs.txt
Labels: in progress

#28001 Add cseku.ac.bd Domain
  lib/domains/bd/ac/cseku.txt
Labels: in progress

#27879 add pro.ac.kr domain
  lib/domains/kr/ac/pro.txt
Labels: in progress

#28101 Add College of Engineering and Management (Ukraine)
  lib/domains/ua/edu/nau/kitu.txt
Labels: in progress

#28118 Evangelisches Gymnasium zum Grauen Kloster
  lib/domains/de/eggk.txt
Labels: in progress

#28077 Added Mischok Academy for JetBrains Student License
  lib/domains/academy/mischok/tn.txt
Labels: in progress

#28094 Bitte aufnehmen
  lib/domains/de/mlg-bad.txt
  lib/domains/schule/bw.txt
Labels: in progress

#28076 Create zespolszkolmechanicznyche.txt
  lib/domains/com/onmicrosoft/zespolszkolmechanicznyche.txt
Labels: in progress

#28072 Student and Trainer Domains at SANTIS Training AG
  lib/domains/ch/santiskurs.txt
  lib/domains/ch/santismail.txt
Labels: in progress

#27918 Request to add Acleda University of Business (@acledaaib.onmicrosoft.com)
  lib/domains/com/onmicrosoft/acledaaib.txt
Labels: in progress

#28008 Add UFA Saint Michel, domain name saintmichelannecy.fr
  lib/domains/fr/saintmichelannecy.txt
Labels: in progress

#28134 Add UEES
  lib/domains/sv/edu/cvirtualuees.txt
Labels: in progress

#28133 Request for Notre-Dame de Bellegarde
  lib/domains/net/ndbellegarde.txt
Labels: in progress

#28207 Add SG Tongerlo
  lib/domains/nl/sgtedu.txt
Labels: in progress

#28106 Add files via upload
  lib/domains/kr/go/goe/samil-th.txt
Labels: in progress

#28232 Create impatech.txt
  lib/domains/br/org/impatech.txt
Labels: in progress

#28220 Add usebeq domain
  lib/domains/mx/edu/usebeq.txt
Labels: in progress

#28283 Create bjalearn.txt
  lib/domains/net/bjalearn.txt
Labels: in progress

#28295 Create beaconite.txt
  lib/domains/pk/edu/beaconite.txt
Labels: in progress

#28326 new file: lib/domains/nl/andreascollege.txt
  lib/domains/nl/andreascollege.txt
Labels: in progress

#28264 Add School San Jose, Malaga.
  lib/domains/net/fundacionloyola.txt
Labels: in progress

#28265 Added kunskapskällan's mail domain
  lib/domains/se/herrljunga/skola.txt
Labels: in progress

#28414 Add files via upload
  lib/domains/ca/qc/college-montreal/educ.txt
Labels: in progress

#28278 Add CSB.SCHOOL to the list of domains
  lib/domains/school/csb.txt
  lib/domains/school/csb/student.txt
Labels: in progress

#28303 Create jedlik.txt
  lib/domains/hu/jedlik.txt
  lib/domains/net/jedlik.txt
Labels: in progress

#28384 Universidad del Valle de México (uvm.mx)
  lib/domains/mx/edu/uvm.txt
Labels: in progress

#27665 ENSET Skikda
  lib/domains/dz/enset-skikda.txt
Labels: in progress

#28210 add Ichthuscollege.net
  lib/domains/net/ichthuscollege.txt
Labels: in progress

#28372 Create thisdl.txt
  lib/domains/cn/thisdl.txt
Labels: in progress

#28454 Add Waseda Saga Junior and Senior High School
  lib/domains/jp/wasedasaga/edu.txt
Labels: in progress

#28500 Add Garstang Community Academy
  lib/domains/uk/org/fcat/garstang.txt
Labels: in progress

#28437 Added @skole.vejle.dk
  lib/domains/dk/vejle/skole.txt
Labels: malformatted, in progress

#28432 Add Jeju International University
  lib/domains/kr/ac/stu.txt
Labels: in progress

#28442 Add hhbkde.txt
  lib/domains/com/onmicrosoft/hhbkde.txt
Labels: in progress

#28449 Added Universitas Boyolali to JetBrains/swot for student verification
  lib/domains/id/ac/uby/mail.txt
Labels: in progress
