Repository JetBrains/swot, pull requests merged in 2025-01, with the labels that each got.

#25971 Create schueler.txt
  lib/domains/de/rs-feucht/schueler.txt
Labels: in progress

#25976 Another school
  lib/domains/pl/edu/zsp1piotrkow.txt
Labels: in progress

#26094 Create zsp10.txt
  lib/domains/pl/edu/elodz/zsp10.txt
Labels: in progress

#25997 Added new domain for new valley university.
  lib/domains/eg/edu/nvu/agr.txt
Labels: in progress

#26001 Add istanbul.txt file via upload
  lib/domains/tr/edu/istanbul.txt
Labels: in progress

#26023 Add Tübitak Fen Lisesi email domain
  lib/domains/tr/k12/tubitakfenlisesi.txt
Labels: in progress

#26034 add Accra Technical University to SWOT repository
  lib/domains/gh/edu/atu.txt
Labels: in progress

#26101 Add files via upload
  lib/domains/uk/org/thpt/threerivers.txt
Labels: in progress

#26112 added SWC
  lib/domains/uk/ac/swc/student.txt
Labels: in progress

#26055 Request to Add a New Domain for Zurich North Cantonal School
  lib/domains/ch/zh/edu/stud.txt
Labels: in progress

#26206 Ibmec professors email extension
  lib/domains/br/edu/ibmec/professores.txt
Labels: in progress

#26134 Add myunfc.txt file to add the school University of Niagara Falls Canada
  lib/domains/ca/myunfc.txt
Labels: in progress

#26152 Add st.cmcu.edu.vn domain for CMC University
  lib/domains/vn/edu/cmcu/st.txt
Labels: in progress

#26160 Add university to jetbrains list
  lib/domains/de/steinbeis-hochschule/student.txt
Labels: in progress

#26263 Rudolph-Brandes-Gymnasium
  lib/domains/nrw/rbg.txt
Labels: in progress

#26137 solicitud para incluir la secretaría de educación de Bogotá, Colombia
  lib/domains/co/edu/educacionbogota.txt
Labels: in progress

#26173 Add primary school in Ozarow Maz.
  lib/domains/pl/sp1ozarow.txt
Labels: in progress

#26179 Add Le Quy Don High School
  lib/domains/vn/edu/lqddn.txt
Labels: in progress

#26186 Add Breck School
  lib/domains/org/breckschool/student.txt
Labels: in progress

#26197 adding domain lions.net
  lib/domains/net/lions.txt
Labels: in progress

#26199 Add My College to Jet Brains List
  lib/domains/uk/ac/sunderlandcollege/my.txt
Labels: in progress

#26207 ZSEE school added
  lib/domains/pl/szczecin/zsee.txt
Labels: in progress

#26360 Add Eastern Maine Community College
  lib/domains/edu/emcc.txt
Labels: failed

#26368 Add files via upload - Gran Faculdade
  lib/domains/br/edu/faculdadegran.txt
Labels: in progress

#26208 Add Fachhochschule der Wirtschaft gGmbH
  lib/domains/de/fhdw/edu.txt
Labels: in progress

#26246 Add ATME COLLEGE OF ENGINEERING
  lib/domains/com/onmicrosoft/atmemys.txt
Labels: in progress

#26309 Create eppuz.txt
  lib/domains/pl/edu/eppuz.txt
Labels: in progress

#26254 Added domain for ETP Xavier
  lib/domains/com/fjaverianas/estudiant.txt
Labels: in progress

#26310 Add files via upload
  lib/domains/kr/ac/kau.txt
Labels: in progress

#26521 St. Michael's College School request
  lib/domains/com/smcsmail.txt
Labels: in progress

#26343 Add files via upload
  lib/domains/id/sch/adisanggoro.txt
Labels: in progress

#26378 Add files via upload
  lib/domains/ph/edu/urs.txt
Labels: in progress

#26332 Can you please add mail.scuole.vda.it ?
  lib/domains/it/vda/scuole/mail.txt
Labels: in progress

#26404 Adding School
  lib/domains/in/gov/delhi/doe.txt
Labels: in progress

#26623 add prof.txt domain
  lib/domains/br/gov/ce/prof.txt
Labels: in progress

#26453 Add University of Balochistan Domain (um.edu.pk)
  lib/domains/pk/edu/uob/um.txt
Labels: in progress

#26423 Added domain tromsfylke.no for Nord-Troms Videregående Skole
  lib/domains/no/tromsfylke.txt
Labels: in progress

#26597 Add: Colégio Objetivo DF, Colégio Ideal and SESI
  lib/domains/br/com/idealbsb/aluno.txt
  lib/domains/br/com/souobjetivodf.txt
  lib/domains/br/org/sesidf.txt
Labels: in progress

#26409 Add ICMS (International College of Management, Sydney) domain
  lib/domains/au/edu/icms/students.txt
Labels: in progress

#26477 Request to add coursdiderot.com
  lib/domains/com/coursdiderot.txt
Labels: in progress

#26484 Add CHA University
  lib/domains/kr/ac/chauniv.txt
Labels: in progress

#26492 Add Kookje University
  lib/domains/kr/ac/kookje.txt
Labels: in progress

#26495 Add files via upload
  lib/domains/pl/zstmikolow.txt
Labels: in progress

#26422 Added email domains for BYU-Pathway Worldwide
  lib/domains/edu/byupathway.txt
Labels: in progress

#26515 Adding the domain of Adigrat University to the repository
  lib/domains/et/edu/adu.txt
Labels: in progress

#26622 Added school detailes for West College Scotland
  lib/domains/uk/ac/wcs/live.txt
Labels: in progress

#26520 Zespół Szkół i Placówek Kształcenia Zawodowego w Bielawie
  lib/domains/com/onmicrosoft/zsipkzwbielawie.txt
Labels: in progress

#26533 Added jda-gex
  lib/domains/education/jda-gex.txt
Labels: in progress

#26564 feat: Add Technological Institute of Ciudad Juárez
  lib/domains/mx/edu/itcj.txt
Labels: in progress

#26611 Create bsregen.txt
  lib/domains/info/bsregen.txt
Labels: in progress

#26617 Add new domain for Mien Trung University of Civil Engineering
  lib/domains/vn/edu/muce.txt
Labels: in progress

#26637 Salesianos.edu domain added
  lib/domains/edu/salesianos/linares.txt
Labels: in progress

#26636 Philippine cultural college
  lib/domains/ph/edu/cultural.txt
Labels: in progress

#26668 Add Universities and secondary schools under Brisbane Catholic Education
  lib/domains/au/edu/catholic/mybce.txt
Labels: whois

#26486 Update nv.txt
  lib/domains/net/ccsd/nv.txt
Labels: in progress

#26511 Deutsche Schule Istanbul
  lib/domains/tr/k12/almanlisesi.txt
Labels: in progress

#26666 Add KD-ICT Professional IT School
  lib/domains/com/kd-ict.txt
Labels: in progress

#26704 Add files via upload
  lib/domains/org/vbisd.txt
Labels: in progress
